const path = require("path");
const { Sequelize, DataTypes } = require("sequelize");

const sequelize = new Sequelize({
    dialect: "sqlite",
    storage: path.join(__dirname, "..", "database.sqlite"),
    logging: false
});

const Config = sequelize.define("Config", {
    strategy: { type: DataTypes.STRING, defaultValue: "spot_grid" },
    pair: { type: DataTypes.STRING, defaultValue: "DOGE/USDT" },
    gridOrderSizeUsdt: { type: DataTypes.FLOAT, defaultValue: 0 },
    gridTargetProfitUsdt: { type: DataTypes.FLOAT, defaultValue: 0.15 },
    maxTradesPerDay: { type: DataTypes.INTEGER, defaultValue: 8 },
    coolingPeriod: { type: DataTypes.INTEGER, defaultValue: 10000 },
    activePosition: { type: DataTypes.TEXT, defaultValue: null },
    activeGridState: { type: DataTypes.TEXT, defaultValue: null },
    dailyPnL: { type: DataTypes.FLOAT, defaultValue: 0 },
    dailyTrades: { type: DataTypes.INTEGER, defaultValue: 0 },
    estimatedPnL: { type: DataTypes.FLOAT, defaultValue: 0 },
    estimatedTrades: { type: DataTypes.INTEGER, defaultValue: 0 },
    dailyPnlSource: { type: DataTypes.STRING, defaultValue: "local" },
    dailyPnlSyncedAt: { type: DataTypes.BIGINT, defaultValue: 0 },
    marginMode: { type: DataTypes.STRING, defaultValue: "spot" },
    monitoringInterval: { type: DataTypes.INTEGER, defaultValue: 500 },
    gridStopLossPercent: { type: DataTypes.FLOAT, defaultValue: 2.4 },
    syncExchangePnl: { type: DataTypes.BOOLEAN, defaultValue: false },

    gridLevels: { type: DataTypes.INTEGER, defaultValue: 0 },
    gridLookbackCandles: { type: DataTypes.INTEGER, defaultValue: 200 },
    gridRangePercent: { type: DataTypes.FLOAT, defaultValue: 0 },
    gridEntryBufferPercent: { type: DataTypes.FLOAT, defaultValue: 0 },
    gridTakeProfitLevels: { type: DataTypes.INTEGER, defaultValue: 0 },
    gridOrdersPerSide: { type: DataTypes.INTEGER, defaultValue: 0 },
    gridAutoOrdersCap: { type: DataTypes.INTEGER, defaultValue: 200 },
    gridStopLossLevels: { type: DataTypes.FLOAT, defaultValue: 0 },

    gridTimeframe: { type: DataTypes.STRING, defaultValue: "5m" },
    sessionStartUTC: { type: DataTypes.INTEGER, defaultValue: 0 },
    sessionEndUTC: { type: DataTypes.INTEGER, defaultValue: 23 },
    volumePeriod: { type: DataTypes.INTEGER, defaultValue: 20 },
    minVolumeRatio: { type: DataTypes.FLOAT, defaultValue: 1.05 },
    atrPeriod: { type: DataTypes.INTEGER, defaultValue: 14 },
    riskRewardRatio: { type: DataTypes.FLOAT, defaultValue: 1.35 },
    trailingEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
    autoStopLossEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
    stopLossAtrMultiplier: { type: DataTypes.FLOAT, defaultValue: 1.4 },
    stopLossMinPercent: { type: DataTypes.FLOAT, defaultValue: 1.2 },
    stopLossMaxPercent: { type: DataTypes.FLOAT, defaultValue: 3.5 },
    autoTargetProfitEnabled: { type: DataTypes.BOOLEAN, defaultValue: true },
    gridRecalculateExitsOnScaleIn: { type: DataTypes.BOOLEAN, defaultValue: true },
    targetProfitAtrMultiplier: { type: DataTypes.FLOAT, defaultValue: 1.8 },
    targetProfitMinUsdt: { type: DataTypes.FLOAT, defaultValue: 0.05 },
    targetProfitMaxUsdt: { type: DataTypes.FLOAT, defaultValue: 1.2 },
    trailingActivateATR: { type: DataTypes.FLOAT, defaultValue: 1.8 },
    trailingOffsetATR: { type: DataTypes.FLOAT, defaultValue: 0.9 },
    entryRsiPeriod: { type: DataTypes.INTEGER, defaultValue: 14 },
    entryRsiLongThreshold: { type: DataTypes.FLOAT, defaultValue: 38 },
    entryRsiShortThreshold: { type: DataTypes.FLOAT, defaultValue: 62 },
    entryAdxPeriod: { type: DataTypes.INTEGER, defaultValue: 14 },
    entryAdxMax: { type: DataTypes.FLOAT, defaultValue: 26 },
    entryBbPeriod: { type: DataTypes.INTEGER, defaultValue: 20 },
    entryBbStdDev: { type: DataTypes.FLOAT, defaultValue: 2 },
    entryBbLongThreshold: { type: DataTypes.FLOAT, defaultValue: 0.18 },
    entryBbShortThreshold: { type: DataTypes.FLOAT, defaultValue: 0.82 },

    lastDailyReset: { type: DataTypes.BIGINT, defaultValue: () => Date.now() },
    lastUpdated: { type: DataTypes.BIGINT, defaultValue: () => Date.now() }
}, { timestamps: false });

const BOOLEAN_CONFIG_KEYS = ["trailingEnabled", "autoTargetProfitEnabled", "autoStopLossEnabled", "gridRecalculateExitsOnScaleIn", "syncExchangePnl"];
const VALID_MARGIN_MODES = ["spot"];
const DEFAULT_CONFIG = {
    strategy: "spot_grid",
    pair: "DOGE/USDT",
    gridOrderSizeUsdt: 0,
    gridTargetProfitUsdt: 0.15,
    maxTradesPerDay: 8,
    coolingPeriod: 10000,
    activePosition: null,
    activeGridState: null,
    dailyPnL: 0,
    dailyTrades: 0,
    estimatedPnL: 0,
    estimatedTrades: 0,
    dailyPnlSource: "local",
    dailyPnlSyncedAt: 0,
    marginMode: "spot",
    monitoringInterval: 500,
    gridStopLossPercent: 2.4,
    syncExchangePnl: false,
    autoStopLossEnabled: true,
    stopLossAtrMultiplier: 1.4,
    stopLossMinPercent: 1.2,
    stopLossMaxPercent: 3.5,
    autoTargetProfitEnabled: true,
    gridRecalculateExitsOnScaleIn: true,
    targetProfitAtrMultiplier: 1.8,
    targetProfitMinUsdt: 0.05,
    targetProfitMaxUsdt: 1.2,
    gridLevels: 0,
    gridLookbackCandles: 200,
    gridRangePercent: 0,
    gridEntryBufferPercent: 0,
    gridTakeProfitLevels: 0,
    gridOrdersPerSide: 0,
    gridAutoOrdersCap: 200,
    gridStopLossLevels: 0,
    gridTimeframe: "5m",
    sessionStartUTC: 0,
    sessionEndUTC: 23,
    volumePeriod: 20,
    minVolumeRatio: 1.05,
    atrPeriod: 14,
    riskRewardRatio: 1.35,
    trailingEnabled: true,
    trailingActivateATR: 1.8,
    trailingOffsetATR: 0.9,
    entryRsiPeriod: 14,
    entryRsiLongThreshold: 38,
    entryRsiShortThreshold: 62,
    entryAdxPeriod: 14,
    entryAdxMax: 26,
    entryBbPeriod: 20,
    entryBbStdDev: 2,
    entryBbLongThreshold: 0.18,
    entryBbShortThreshold: 0.82
};

const DASHBOARD_EDITABLE_FIELDS = [
    { key: "strategy", label: "Strategy", section: "General", type: "select", options: ["spot_grid"], description: "Main strategy used by the bot." },
    { key: "pair", label: "Pair", section: "General", type: "text", placeholder: "DOGE/USDT", description: "Spot symbol to trade." },
    { key: "monitoringInterval", label: "Monitoring Interval", section: "General", type: "number", min: 200, step: 100, description: "PnL monitoring interval in milliseconds." },
    { key: "coolingPeriod", label: "Cooling Period", section: "General", type: "number", min: 0, step: 500, description: "Cooldown after a trade in milliseconds. Set 0 to disable cooldown." },
    { key: "gridOrderSizeUsdt", label: "Grid Order Size (USDT)", section: "Risk", type: "number", min: 0, step: 0.1, description: "Order size per grid entry in USDT. Set 0 for automatic sizing." },
    { key: "autoTargetProfitEnabled", label: "Auto Target Profit", section: "Risk", type: "boolean", description: "Use ATR-based TP with a capped range instead of a fixed profit." },
    { key: "gridRecalculateExitsOnScaleIn", label: "Recalculate TP/SL on Scale-In", section: "Risk", type: "boolean", description: "When enabled, every additional filled grid entry recalculates TP/SL from the latest average entry and total position size." },
    { key: "targetProfitAtrMultiplier", label: "TP ATR Multiplier", section: "Risk", type: "number", min: 0.1, step: 0.05, description: "ATR multiplier used to derive automatic target profit." },
    { key: "targetProfitMinUsdt", label: "TP Min (USDT)", section: "Risk", type: "number", min: 0, step: 0.05, description: "Lower bound for automatic target profit." },
    { key: "targetProfitMaxUsdt", label: "TP Max (USDT)", section: "Risk", type: "number", min: 0, step: 0.1, description: "Upper bound for automatic target profit." },
    { key: "autoStopLossEnabled", label: "Auto Stop Loss", section: "Risk", type: "boolean", description: "Use ATR-based stop loss with a capped range instead of a fixed percentage." },
    { key: "stopLossAtrMultiplier", label: "SL ATR Multiplier", section: "Risk", type: "number", min: 0.05, step: 0.05, description: "ATR multiplier used to derive automatic stop loss." },
    { key: "stopLossMinPercent", label: "SL Min (%)", section: "Risk", type: "number", min: 0, step: 0.1, description: "Lower bound for automatic stop loss percent." },
    { key: "stopLossMaxPercent", label: "SL Max (%)", section: "Risk", type: "number", min: 0, step: 0.1, description: "Upper bound for automatic stop loss percent." },
    { key: "maxTradesPerDay", label: "Max Trades Per Day", section: "Risk", type: "number", min: 1, step: 1, description: "Daily trade cap." },
    { key: "minVolumeRatio", label: "Min Volume Ratio", section: "Risk", type: "number", min: 1, step: 0.1, description: "Minimum volume filter." },
    { key: "riskRewardRatio", label: "Reward/Risk Ratio", section: "Risk", type: "number", min: 0.5, step: 0.1, description: "Take-profit multiple applied to normalized stop distance." },
    { key: "gridLevels", label: "Grid Levels", section: "Grid", type: "number", min: 0, step: 1, description: "Number of levels in the grid. Set 0 for automatic mode." },
    { key: "gridLookbackCandles", label: "Lookback Candles", section: "Grid", type: "number", min: 20, step: 1, description: "Candles used to calculate the grid range." },
    { key: "gridRangePercent", label: "Range (%)", section: "Grid", type: "number", min: 0, step: 0.1, description: "Grid range width in percent. Set 0 for automatic mode." },
    { key: "gridEntryBufferPercent", label: "Entry Buffer (%)", section: "Grid", type: "number", min: 0, step: 0.01, description: "Buffer around grid levels for entries. Set 0 for automatic mode." },
    { key: "gridTakeProfitLevels", label: "Take Profit Levels", section: "Grid", type: "number", min: 0, step: 1, description: "TP level offset from the entry level. Set 0 for automatic TP mode." },
    { key: "gridOrdersPerSide", label: "Orders Per Side", section: "Grid", type: "number", min: 0, step: 1, description: "Number of ladder orders per side. Set 0 for automatic order count." },
    { key: "gridAutoOrdersCap", label: "Auto Orders Cap", section: "Grid", type: "number", min: 1, step: 1, description: "Maximum ladder orders per side when Orders Per Side is set to 0 (AUTO)." },
    { key: "gridStopLossLevels", label: "Stop Loss Levels", section: "Grid", type: "number", min: 0, step: 0.1, description: "Stop loss offset in grid steps. Set 0 for automatic SL mode." },
    { key: "gridTimeframe", label: "Grid Timeframe", section: "Grid", type: "select", options: ["1m", "3m", "5m", "15m", "30m", "1h", "4h", "1d"], description: "Timeframe used to build the grid." },
    { key: "sessionStartUTC", label: "Session Start UTC", section: "Session", type: "number", min: 0, max: 23, step: 1, description: "Trading session start hour in UTC." },
    { key: "sessionEndUTC", label: "Session End UTC", section: "Session", type: "number", min: 0, max: 23, step: 1, description: "Trading session end hour in UTC." },
    { key: "volumePeriod", label: "Volume Period", section: "Session", type: "number", min: 2, step: 1, description: "Volume lookback period." },
    { key: "atrPeriod", label: "ATR Period", section: "Session", type: "number", min: 2, step: 1, description: "ATR calculation period." },
    { key: "trailingEnabled", label: "Trailing Enabled", section: "Trailing", type: "boolean", description: "Enable trailing stop logic." },
    { key: "trailingActivateATR", label: "Trail Activate ATR", section: "Trailing", type: "number", min: 0.2, step: 0.1, description: "ATR multiple needed before trailing starts." },
    { key: "trailingOffsetATR", label: "Trail Offset ATR", section: "Trailing", type: "number", min: 0.1, step: 0.1, description: "ATR offset used by the trailing stop." },
    { key: "entryRsiPeriod", label: "RSI Period", section: "Entry Filters", type: "number", min: 2, step: 1, description: "RSI lookback used by the universal entry filter." },
    { key: "entryRsiLongThreshold", label: "RSI Long Max", section: "Entry Filters", type: "number", min: 1, max: 50, step: 1, description: "Maximum RSI allowed for long mean-reversion entries." },
    { key: "entryRsiShortThreshold", label: "RSI Short Min", section: "Entry Filters", type: "number", min: 50, max: 99, step: 1, description: "Minimum RSI required for short mean-reversion entries." },
    { key: "entryAdxPeriod", label: "ADX Period", section: "Entry Filters", type: "number", min: 2, step: 1, description: "ADX lookback used to reject strong-trend mean-reversion trades." },
    { key: "entryAdxMax", label: "ADX Max", section: "Entry Filters", type: "number", min: 5, step: 1, description: "Maximum ADX allowed before entries are blocked." },
    { key: "entryBbPeriod", label: "BB Period", section: "Entry Filters", type: "number", min: 5, step: 1, description: "Bollinger Band period used for entry normalization." },
    { key: "entryBbStdDev", label: "BB Std Dev", section: "Entry Filters", type: "number", min: 1, step: 0.1, description: "Bollinger Band standard deviation width." },
    { key: "entryBbLongThreshold", label: "BB Long %B Max", section: "Entry Filters", type: "number", min: 0, max: 0.5, step: 0.05, description: "Maximum Bollinger %B allowed for long entries." },
    { key: "entryBbShortThreshold", label: "BB Short %B Min", section: "Entry Filters", type: "number", min: 0.5, max: 1, step: 0.05, description: "Minimum Bollinger %B required for short entries." }
];

const DASHBOARD_EDITABLE_KEYS = new Set(DASHBOARD_EDITABLE_FIELDS.map((field) => field.key));
const RUNTIME_PROTECTED_CONFIG_KEYS = ["strategy", "pair", "marginMode", "gridTimeframe"];
const DASHBOARD_PROTECTED_KEYS = new Set(RUNTIME_PROTECTED_CONFIG_KEYS);
const DASHBOARD_USERNAME = String(process.env.DASHBOARD_USERNAME || "admin");
const DASHBOARD_PASSWORD = String(process.env.DASHBOARD_PASSWORD || "admin123");
const DASHBOARD_SESSION_SECRET = String(process.env.DASHBOARD_SESSION_SECRET || process.env.API_SECRET || "smart-bot-dashboard-secret");
const DASHBOARD_SESSION_COOKIE = "smartbot_dashboard_session";
const DASHBOARD_SESSION_TTL_MS = 12 * 60 * 60 * 1000;
const CONFIG_AUTO_RELOAD_INTERVAL_MS = Math.max(3000, Math.trunc(Number(process.env.CONFIG_AUTO_RELOAD_INTERVAL_MS || 5000) || 5000));

module.exports = {
    sequelize,
    Config,
    BOOLEAN_CONFIG_KEYS,
    VALID_MARGIN_MODES,
    DEFAULT_CONFIG,
    DASHBOARD_EDITABLE_FIELDS,
    DASHBOARD_EDITABLE_KEYS,
    RUNTIME_PROTECTED_CONFIG_KEYS,
    DASHBOARD_PROTECTED_KEYS,
    DASHBOARD_USERNAME,
    DASHBOARD_PASSWORD,
    DASHBOARD_SESSION_SECRET,
    DASHBOARD_SESSION_COOKIE,
    DASHBOARD_SESSION_TTL_MS,
    CONFIG_AUTO_RELOAD_INTERVAL_MS
};
